import type { Child } from '@/lib/types'

export const mockChildren: Child[] = [
  {
    id: 'ch1',
    name: 'Emma Okafor',
    age: 7,
    dateOfBirth: '2018-09-14',
    diagnoses: ['Autism Spectrum Disorder', 'Sensory Processing Disorder'],
    supportNeeds: [
      'Sensory regulation support',
      'Visual schedule & routine predictability',
      'Social communication scaffolding',
      'Noise-reduction accommodations',
    ],
    strengths: [
      'Exceptional visual-spatial memory',
      'Deep focus on areas of interest',
      'Kind and empathetic with trusted adults',
    ],
    interests: ['Dinosaurs', 'Drawing', 'Building with LEGO', 'Classical music'],
    routines: [
      'Morning visual schedule before school',
      'Sensory break after 45 minutes of work',
      'Quiet wind-down time before bed',
      'Weighted blanket at sleep',
    ],
    goals: [
      'Initiate peer interactions 2x per school day',
      'Tolerate unexpected schedule changes with one verbal prompt',
      'Use "I need a break" card independently',
      'Expand preferred food variety to 3 new textures',
    ],
    notes: 'Emma thrives with advance notice and clear expectations. She responds well to visual supports and prefers working one-on-one or in small groups of 2. Her sensory profile indicates heightened sensitivity to auditory and tactile input.',
    avatarColor: 'sage',
    createdAt: '2026-01-15',
  },
  {
    id: 'ch2',
    name: 'Liam Chen',
    age: 5,
    dateOfBirth: '2020-11-03',
    diagnoses: ['Expressive Language Delay', 'Apraxia of Speech'],
    supportNeeds: [
      'AAC device modeling and support',
      'Augmentative communication strategies',
      'Reduced verbal demand during stress',
      'Core vocabulary exposure',
    ],
    strengths: [
      'Strong receptive language comprehension',
      'Highly motivated by music and rhythm',
      'Persistent and curious learner',
    ],
    interests: ['Songs and nursery rhymes', 'Cars and trucks', 'Water play', 'Puppets'],
    routines: [
      'AAC device available at all times',
      'Daily reading with rich language modeling',
      'Music activity before transitions',
      'Practice core vocabulary during play',
    ],
    goals: [
      'Use AAC to make requests across 3 environments',
      'Combine 2-symbol messages consistently',
      'Participate in circle time with AAC for 10 minutes',
      'Use AAC to reject or protest appropriately',
    ],
    notes: 'Liam uses a Tobii Dynavox for communication. His team uses aided language stimulation throughout the day. He shows strong understanding of routines and responds well to music-based transitions. Patience and wait time are critical — allow 10 seconds before prompting.',
    avatarColor: 'dblue',
    createdAt: '2026-02-08',
  },
  {
    id: 'ch3',
    name: 'Sophia Martinez',
    age: 10,
    dateOfBirth: '2015-04-22',
    diagnoses: ['ADHD (Combined Type)', 'Dyslexia'],
    supportNeeds: [
      'Executive function scaffolding',
      'Chunked tasks with clear checkpoints',
      'Preferential seating away from distractions',
      'Extended time and read-aloud accommodations',
    ],
    strengths: [
      'Creative problem-solver',
      'Strong verbal reasoning and storytelling',
      'Natural leader among peers',
    ],
    interests: ['Art and crafts', 'Soccer', 'Podcasts', 'Animals', 'Cooking with family'],
    routines: [
      'Homework directly after a 20-minute active break',
      'Use of planner/checklist for multi-step tasks',
      'Fidget tools available during seated work',
      'Daily reading practice with decodable texts',
    ],
    goals: [
      'Complete multi-step tasks with 1 reminder (not 3+)',
      'Read grade-level passages with 85% accuracy',
      'Self-monitor attention using visual timer',
      'Organize backpack and materials independently',
    ],
    notes: 'Sophia benefits enormously from movement breaks and hands-on learning. Her dyslexia responds well to structured literacy approaches (Orton-Gillingham). She is socially motivated and works harder when tasks feel purposeful. Avoid public correction — private redirection is far more effective.',
    avatarColor: 'sand',
    createdAt: '2026-01-22',
  },
  {
    id: 'ch4',
    name: 'Noah Patel',
    age: 9,
    dateOfBirth: '2016-07-30',
    diagnoses: ['Spastic Diplegia Cerebral Palsy', 'Mild Intellectual Disability'],
    supportNeeds: [
      'Fine and gross motor accommodations',
      'Adapted seating and positioning',
      'Modified writing tools and keyboard access',
      'Concrete, visual instructional supports',
    ],
    strengths: [
      'Warm, joyful presence with strong social bonds',
      'Excellent memory for people and stories',
      'Determined and motivated by achievement',
    ],
    interests: ['Sports (watching and discussing)', 'Superhero stories', 'Cooking shows', 'Board games'],
    routines: [
      'PT exercises integrated into morning routine',
      'Adaptive PE three times per week',
      'Occupational therapy for fine motor twice weekly',
      'Movement break between academic blocks',
    ],
    goals: [
      'Use adaptive keyboard to complete written assignments independently',
      'Improve functional walking endurance to 200m',
      'Participate in cooperative group tasks with peer support',
      'Increase self-care independence (dressing, lunch prep)',
    ],
    notes: 'Noah uses a walker for longer distances and standard seating with lumbar support for seated work. He is highly socially motivated and benefits from cooperative learning structures. His intellectual profile is strongest in language and social comprehension. Always presume competence.',
    avatarColor: 'sage',
    createdAt: '2026-03-01',
  },
]
