import type { Document } from '@/lib/types'

export const mockDocuments: Document[] = [
  {
    id: 'd1',
    name: 'ASHA SPD Clinical Guidelines 2024.pdf',
    type: 'pdf',
    sizeKb: 2840,
    status: 'ready',
    uploadedBy: 'Admin',
    uploadedAt: '2026-03-01',
    tags: ['clinical', 'SPD', 'ASHA'],
    chunkCount: 142,
  },
  {
    id: 'd2',
    name: 'IEP Goal Bank — Literacy & Communication.docx',
    type: 'docx',
    sizeKb: 890,
    status: 'ready',
    uploadedBy: 'Maya Thornton',
    uploadedAt: '2026-03-15',
    tags: ['IEP', 'literacy', 'communication'],
    chunkCount: 67,
  },
  {
    id: 'd3',
    name: 'Sensory Diet Activity Handbook.pdf',
    type: 'pdf',
    sizeKb: 4210,
    status: 'ready',
    uploadedBy: 'Admin',
    uploadedAt: '2026-02-20',
    tags: ['sensory', 'OT', 'activities'],
    chunkCount: 198,
  },
  {
    id: 'd4',
    name: 'AAC Implementation Roadmap 2025.pdf',
    type: 'pdf',
    sizeKb: 1650,
    status: 'processing',
    uploadedBy: 'Admin',
    uploadedAt: '2026-04-06',
    tags: ['AAC', 'communication'],
    chunkCount: undefined,
  },
  {
    id: 'd5',
    name: 'Behavior Support Plans — Template Library.pdf',
    type: 'pdf',
    sizeKb: 3100,
    status: 'ready',
    uploadedBy: 'Carlos Reyes',
    uploadedAt: '2026-03-22',
    tags: ['behavior', 'BSP', 'PBS'],
    chunkCount: 211,
  },
  {
    id: 'd6',
    name: 'Autism Spectrum Conditions — Parent Guide.pdf',
    type: 'pdf',
    sizeKb: 1980,
    status: 'ready',
    uploadedBy: 'Maya Thornton',
    uploadedAt: '2026-03-10',
    tags: ['autism', 'parents', 'guide'],
    chunkCount: 98,
  },
  {
    id: 'd7',
    name: 'ADHD Classroom Accommodations Checklist.docx',
    type: 'docx',
    sizeKb: 340,
    status: 'error',
    uploadedBy: 'Admin',
    uploadedAt: '2026-04-05',
    tags: ['ADHD', 'classroom', 'IEP'],
    chunkCount: undefined,
  },
]
