import type { Document } from '@/lib/types'

export const mockDocuments: Document[] = [
  {
    id: 'd1',
    title: 'ASHA SPD Clinical Guidelines 2024',
    originalFilename: 'ASHA SPD Clinical Guidelines 2024.pdf',
    type: 'pdf',
    fileSizeBytes: 2840 * 1024,
    storagePath: 'mock/d1.pdf',
    status: 'ready',
    uploadedBy: null,
    uploadedAt: '2026-03-01',
    processedAt: '2026-03-01',
    tags: ['clinical', 'SPD', 'ASHA'],
    chunkCount: 142,
    errorMessage: null,
  },
  {
    id: 'd2',
    title: 'IEP Goal Bank — Literacy & Communication',
    originalFilename: 'IEP Goal Bank — Literacy & Communication.docx',
    type: 'docx',
    fileSizeBytes: 890 * 1024,
    storagePath: 'mock/d2.docx',
    status: 'ready',
    uploadedBy: null,
    uploadedAt: '2026-03-15',
    processedAt: '2026-03-15',
    tags: ['IEP', 'literacy', 'communication'],
    chunkCount: 67,
    errorMessage: null,
  },
  {
    id: 'd3',
    title: 'Sensory Diet Activity Handbook',
    originalFilename: 'Sensory Diet Activity Handbook.pdf',
    type: 'pdf',
    fileSizeBytes: 4210 * 1024,
    storagePath: 'mock/d3.pdf',
    status: 'ready',
    uploadedBy: null,
    uploadedAt: '2026-02-20',
    processedAt: '2026-02-20',
    tags: ['sensory', 'OT', 'activities'],
    chunkCount: 198,
    errorMessage: null,
  },
  {
    id: 'd4',
    title: 'AAC Implementation Roadmap 2025',
    originalFilename: 'AAC Implementation Roadmap 2025.pdf',
    type: 'pdf',
    fileSizeBytes: 1650 * 1024,
    storagePath: 'mock/d4.pdf',
    status: 'embedding',
    uploadedBy: null,
    uploadedAt: '2026-04-06',
    processedAt: null,
    tags: ['AAC', 'communication'],
    chunkCount: 0,
    errorMessage: null,
  },
  {
    id: 'd5',
    title: 'Behavior Support Plans — Template Library',
    originalFilename: 'Behavior Support Plans — Template Library.pdf',
    type: 'pdf',
    fileSizeBytes: 3100 * 1024,
    storagePath: 'mock/d5.pdf',
    status: 'ready',
    uploadedBy: null,
    uploadedAt: '2026-03-22',
    processedAt: '2026-03-22',
    tags: ['behavior', 'BSP', 'PBS'],
    chunkCount: 211,
    errorMessage: null,
  },
  {
    id: 'd6',
    title: 'Autism Spectrum Conditions — Parent Guide',
    originalFilename: 'Autism Spectrum Conditions — Parent Guide.pdf',
    type: 'pdf',
    fileSizeBytes: 1980 * 1024,
    storagePath: 'mock/d6.pdf',
    status: 'ready',
    uploadedBy: null,
    uploadedAt: '2026-03-10',
    processedAt: '2026-03-10',
    tags: ['autism', 'parents', 'guide'],
    chunkCount: 98,
    errorMessage: null,
  },
  {
    id: 'd7',
    title: 'ADHD Classroom Accommodations Checklist',
    originalFilename: 'ADHD Classroom Accommodations Checklist.docx',
    type: 'docx',
    fileSizeBytes: 340 * 1024,
    storagePath: 'mock/d7.docx',
    status: 'failed',
    uploadedBy: null,
    uploadedAt: '2026-04-05',
    processedAt: null,
    tags: ['ADHD', 'classroom', 'IEP'],
    chunkCount: 0,
    errorMessage: 'Text extraction failed: encrypted document',
  },
]
