import type { User } from '@/lib/types'

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Maya Thornton',
    email: 'maya@brightpath.org',
    role: 'clinician',
    status: 'active',
    organization: 'BrightPath Therapy',
    joinedAt: '2024-09-12',
    lastActiveAt: '2026-04-05',
    avatarUrl: 'https://placehold.co/40x40/C6D6BE/385432?text=MT',
  },
  {
    id: 'u2',
    name: 'James Okafor',
    email: 'james.okafor@gmail.com',
    role: 'parent',
    status: 'active',
    joinedAt: '2025-01-03',
    lastActiveAt: '2026-04-06',
    avatarUrl: 'https://placehold.co/40x40/DDE4EE/2D4365?text=JO',
  },
  {
    id: 'u3',
    name: 'Priya Nair',
    email: 'p.nair@sunriseschool.edu',
    role: 'teacher',
    status: 'invited',
    organization: 'Sunrise Special Ed',
    joinedAt: '2026-03-28',
    lastActiveAt: '2026-03-28',
    avatarUrl: 'https://placehold.co/40x40/E4EBE0/385432?text=PN',
  },
  {
    id: 'u4',
    name: 'Carlos Reyes',
    email: 'creyes@familyfirst.com',
    role: 'caregiver',
    status: 'active',
    organization: 'Family First Support',
    joinedAt: '2025-06-15',
    lastActiveAt: '2026-04-04',
    avatarUrl: 'https://placehold.co/40x40/C6D6BE/2D4365?text=CR',
  },
  {
    id: 'u5',
    name: 'Leila Haddad',
    email: 'l.haddad@brightpath.org',
    role: 'clinician',
    status: 'suspended',
    organization: 'BrightPath Therapy',
    joinedAt: '2024-11-20',
    lastActiveAt: '2026-02-14',
    avatarUrl: 'https://placehold.co/40x40/DDE4EE/1E2D46?text=LH',
  },
  {
    id: 'u6',
    name: 'Sarah Whitmore',
    email: 's.whitmore@cedarvalley.edu',
    role: 'teacher',
    status: 'active',
    organization: 'Cedar Valley School District',
    joinedAt: '2025-08-01',
    lastActiveAt: '2026-04-03',
    avatarUrl: 'https://placehold.co/40x40/F5EFE0/7C4A1F?text=SW',
  },
]

export const mockCurrentUser: User = {
  id: 'u0',
  name: 'Alex Rivera',
  email: 'alex@brightpath.org',
  role: 'admin',
  status: 'active',
  organization: 'BrightPath Therapy',
  joinedAt: '2024-01-01',
  lastActiveAt: '2026-04-06',
}
